import type { NavItem } from "#/types/nav";

export const adminNavItems: NavItem[] = [
  { title: "Affiliate Report", to: "/admin" },
  { title: "Affiliates", to: "/admin" },
  { title: "Aircraft Types", to: "/admin" },
  { title: "Airline Info CMS", to: "/admin" },
  { title: "Airlines", to: "/admin" },
  { title: "Alliances", to: "/admin/alliances" },
  { title: "Ancillaries Settings", to: "/admin" },
  { title: "AutoCharge Rules", to: "/admin" },
  { title: "Automated Refunds", to: "/admin" },
  { title: "AutoTicket Report", to: "/admin" },
  { title: "AutoTicket Rules", to: "/admin" },
  { title: "Baggage Advice Rules", to: "/admin" },
  { title: "Baggage Rules", to: "/admin" },
  { title: "Batch PNR Lookup", to: "/admin" },
  { title: "Batch Rule Upload", to: "/admin" },
  { title: "Booking and Service Fees CMS", to: "/admin" },
  { title: "Booking Email Preview", to: "/admin" },
  { title: "Booking Query Log", to: "/admin" },
  { title: "Booking Recovery", to: "/admin" },
  { title: "Booking Rules", to: "/admin" },
  { title: "Cache Management", to: "/admin" },
  { title: "Cancel PNR", to: "/admin" },
  { title: "Change Password", to: "/admin" },
  { title: "Cities and Airports", to: "/admin" },
  { title: "CMS", to: "/admin" },
  { title: "Continents", to: "/admin" },
  { title: "Contribution to overhead", to: "/admin" },
  { title: "Corporate Credit Cards", to: "/admin" },
  { title: "Countries", to: "/admin" },
  { title: "Customer Advice Rules", to: "/admin" },
  { title: "Customer Support Tools", to: "/admin" },
  { title: "Delay Ticketing Rules", to: "/admin" },
  { title: "Destination CMS", to: "/admin" },
  { title: "Domain Conversion URL", to: "/admin" },
  { title: "Domains", to: "/admin" },
  { title: "Exchange Rates", to: "/admin" },
  { title: "Exclusion Rules", to: "/admin" },
  { title: "Fee Rules", to: "/admin" },
  { title: "Flight Query Rules", to: "/admin" },
  { title: "Flight Query Rules (Incremental)", to: "/admin" },
  { title: "Flight Query Rules (Revalidate)", to: "/admin" },
  { title: "Flight Vouchers", to: "/admin" },
  { title: "Get PNR", to: "/admin" },
  { title: "Google Flights Fee Rules Upload", to: "/admin" },
  { title: "Homepage CMS", to: "/admin" },
  { title: "Import / Export Data", to: "/admin" },
  { title: "Landing Page CMS", to: "/admin" },
  { title: "Margin Rules", to: "/admin" },
  { title: "Margin Rules Upload", to: "/admin" },
  { title: "Metasearch Multi-city Rules", to: "/admin" },
  { title: "Metasearch Rules", to: "/admin" },
  { title: "Mileages", to: "/admin" },
  { title: "Net Income Percentages", to: "/admin" },
  { title: "One Way Aggregate Rules", to: "/admin" },
  { title: "Operations Rules", to: "/admin" },
  { title: "Payment Offer Rules", to: "/admin" },
  { title: "Payment Processing", to: "/admin" },
  { title: "Payment Processing Reporting", to: "/admin" },
  { title: "Payment Type Rules", to: "/admin" },
  { title: "Product Selection Rules", to: "/admin" },
  { title: "Purchase Travel Insurance", to: "/admin" },
  { title: "Reconciliation Upload", to: "/admin" },
  { title: "Reports", to: "/admin" },
  { title: "Resend Customer Confirmation Email", to: "/admin" },
  { title: "Sabre Sales Report", to: "/admin" },
  {
    title: "SEO",
    to: "/admin",
    children: [
      { title: "Cheap Flights", to: "/admin" },
      { title: "Meta Tags", to: "/admin" },
    ],
  },
  { title: "Settings", to: "/admin" },
  { title: "Supplier Booking Upload", to: "/admin" },
  { title: "Ticketing Form of Payment", to: "/admin" },
  { title: "Trace Tool", to: "/admin" },
  { title: "Update E-Ticket Airlines", to: "/admin" },
  { title: "Update Frequent Flyer Airlines", to: "/admin" },
  { title: "Update Purchased Ancillary", to: "/admin" },
  { title: "User Management", to: "/admin" },
  { title: "Virtual Credit Card Generator", to: "/admin" },
  { title: "WebFare Booking Queries", to: "/admin" },
];
