import { readFileSync, writeFileSync } from "fs";

const files = {
  schema: "src/db/schema/schema.ts",
  relations: "src/db/schema/relations.ts",
};

function clean(path: string, transforms: Array<[RegExp, string, string]>) {
  let content = readFileSync(path, "utf-8");
  const applied: string[] = [];
  for (const [pattern, replacement, description] of transforms) {
    const updated = content.replaceAll(pattern, replacement);
    if (updated !== content) {
      applied.push(description);
      content = updated;
    }
  }
  writeFileSync(path, content, "utf-8");
  if (applied.length > 0) {
    console.log(`Cleaned ${path}:\n${applied.map((d) => `  - ${d}`).join("\n")}`);
  } else {
    console.log(`Cleaned ${path}: no changes needed`);
  }
}

// Fix broken default(') values generated by drizzle-kit pull (missing closing quote)
clean(files.schema, [[/\.default\('\)/g, ".default('')", "Fixed malformed .default(') → .default('')"]]);

// Remove schema suffix from exported variable names (e.g. allianceInDbo → alliance)
const stripSchemaSuffix: Array<[RegExp, string, string]> = [
  [/InDbo/g, "", "Removed 'InDbo' suffix from exported variable names"],
];
clean(files.schema, stripSchemaSuffix);
clean(files.relations, stripSchemaSuffix);
